.\" Created by Arif on 10-03-2018 for teaching purpose (anolgajbhiye99@gmail.com)
.TH MYADD 3  10-03-2018 "GNU" "Linux Programmer's Manual"
.SH NAME
add \- add two numbers
.SH SYNOPSIS
.nf
.B #include <mymath.h>
.sp
.BI "float add(float n1, float n2);

.fi
.SH DESCRIPTION
.BR add()
is passed two numbers and it adds them up and returns their sum

.SH CONFORMING TO
POSIX.1-2001, POSIX.1-2008, C89, C99.

.SH SEE ALSO
.BR sub (3),
.BR mul (3),
.BR div (3),
.BR mod (3),
.SH COLOPHON
This page is part of release 4.10 of the Linux
.I man-pages
project.
A description of the project,
information about reporting bugs,
and the latest version of this page,
can be found at
\%https://www.kernel.org/doc/man\-pages/.

